### ISSUE TITLE
Change overview in docs to __dbt-privacy__ instead of __overview__

### ISSUE THREAD

**Issue by VillainGuy** [pvcy/dbt-privacy#11]
While generating docs dbt will overwrite the default overview with files matching overview.md and including {% docs __overview__ %}.
Because of this installing the dbt-privacy package will overwrite the default overview, even if another overview.md is provided.

**Comment by tconbeer** [comment]
I had no idea -- thought that was scoped per-project already. I'll release a fix for this asap

**Comment by tconbeer** [comment]
Just cut a v0.2.1 release for this. Should be on the Hub later today. Thanks for the report!
